name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LHCI: ${{ secrets.LHCI }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run images:ingest
      - run: node scripts/check-images.mjs
      - run: npm run build
      - name: Lighthouse (optional)
        if: env.LHCI == '1'
        run: |
          npx @lhci/cli autorun || echo "LHCI optional"
